# matching_pesos.yml — pesos e limiares do motor de conferência
version: 1.0

limiares:
  auto_match: 70          # >= auto
  pendente_min: 50        # 50..69 = pendente
  max_candidates: 6
  janela_default_dias: 3

estrategias:
  S1: 50                  # Documento + Participante + Valor (exato)
  S2: 35                  # Documento + Participante + Data (janela)
  S3: 25                  # Documento + Valor + Data
  S4: 20                  # Valor + Participante + Data
  S5: 10                  # Indícios por regex/tokens (apoio)
  S6: 0                   # Validação CFOP×Contas (aplica bônus/penalidade)

bonus:
  participante_exato: 10
  participante_nome_fuzzy_alto: 4
  valor_exato_centavos: 6
  valor_dentro_tolerancia: 3
  data_mesma: 4
  data_ate_1_dia: 6
  data_ate_3_dias: 3
  cfop_contas_coerente: 5
  token_forte: 4          # NFE_NUM_SERIE, NFSE_RPS, CARTAO_ADQ
  mesmo_mes_ref: 2
  fonte_prioritaria: 2    # quando a fonte é preferencial no perfil ativo

penalidades:
  participante_conflito: -15
  cfop_contas_conflito: -10
  documento_cancelado: -25
  valor_fora_tolerancia: -40
  data_fora_janela: -20
  duplicado_mesmo_documento: -8
  modelo_inconsistente: -4   # ex.: modelo fiscal incompatível com a operação
  situacao_irregular: -6     # ex.: inutilizado, denegado etc.

desempate:
  ordem: [delta_valor_abs, delta_dias_abs, prioridade_fonte, score]
  pesos:
    delta_valor_abs: 0.70   # menor diferença de valor vence
    delta_dias_abs: 0.20    # depois menor distância de datas
    prioridade_fonte: 0.10  # ENTRADA/SAIDA > SERVICO por padrão (ajustável)
  prioridade_fonte:
    ENTRADA: 1.0
    SAIDA: 1.0
    SERVICO: 0.9

ajustes_contextuais:
  # Ajustes dinâmicos por contexto (somados ao score)
  CFOP:
    "1102": {bonus: 2}      # casamentos de compra/estoque ganham folga positiva
    "5102": {bonus: 2}
    "6102": {bonus: 2}
    "1556": {bonus: 1}
  CONTA:
    "3.1.1.01.0001": {bonus: 2}   # receitas cartão
    "1.1.1.02.0001": {bonus: 1}   # bancos
  FONTE:
    ENTRADA: {bonus: 1}
    SAIDA: {bonus: 1}
    SERVICO: {bonus: 0}

# Modo estrito (para fechamento/entrega): sobe limiares e endurece penalidades
modos:
  padrao:
    <<: *default
  estrito:
    limiares:
      auto_match: 80
      pendente_min: 60
    penalidades:
      participante_conflito: -20
      cfop_contas_conflito: -15
      valor_fora_tolerancia: -50
      data_fora_janela: -25

tests:
  - name: "S1 perfeito"
    inputs: {estrategia: "S1", participante_exato: true, valor_exato_centavos: true, data_mesma: true}
    expect: {score_min: 80}
  - name: "S2 data até 3 dias, valor na tolerância"
    inputs: {estrategia: "S2", valor_dentro_tolerancia: true, data_ate_3_dias: true}
    expect: {score_min: 60, status: "pendente|auto"}
  - name: "Conflito de participante derruba"
    inputs: {estrategia: "S1", participante_conflito: true}
    expect: {score_max: 40, status: "sem_fonte"}
