# regex_tokens.yml
# Padrões para extrair INDÍCIOS (tokens) de histórico/complemento e auxiliar o S5.
# Convenções:
#  - Sempre normalize o texto (UPPERCASE, sem acentos) antes de aplicar.
#  - 'captures' define os nomes dos grupos. Pós-processamentos em 'post'.
#  - Estes tokens NÃO são chaves de casamento por si; servem para reforçar candidatos.
#  - Pontuações sugeridas em 'score_boosts' (aplicadas pelo motor S5).

version: 1.0
normalize:
  uppercase: true
  strip: true
  remove_accents: true
  collapse_spaces: true

patterns:
  - id: NFE_NUM_SERIE
    description: "NF-e/NF com número e série: 'NFE 14959/002', 'NF 1234-1'."
    regex: "\b(?:NF(?:-?E)?|NFS?-?E?)\s*(\d{1,10})(?:[\/\-](\d{1,3}))?\b"
    captures: [doc_num, doc_serie]
    post:
      doc_num_norm: "digits(doc_num)"
      doc_serie_norm: "lstrip_zeros(doc_serie)"
  - id: DCTO_NUM
    description: "Número de documento explícito: 'DCTO14959', 'DCTO 12345'."
    regex: "\bDCTO\s*([0-9]{1,12})\b"
    captures: [doc_num]
    post:
      doc_num_norm: "digits(doc_num)"
  - id: FATURA_NUM
    description: "Fatura com opcional de série: 'FAT 1234/1', 'FATURA 9876-02'."
    regex: "\bFAT(?:URA)?\s*(\d{1,12})(?:[\/\-](\d{1,3}))?\b"
    captures: [doc_num, doc_serie]
    post:
      doc_num_norm: "digits(doc_num)"
      doc_serie_norm: "lstrip_zeros(doc_serie)"
  - id: DUPLICATA_NUM
    description: "Duplicata: 'DUP 12345', 'DUPLICATA 54321'."
    regex: "\bDU?P(?:LICATA)?\s*(\d{1,12})\b"
    captures: [doc_num]
    post:
      doc_num_norm: "digits(doc_num)"
  - id: PIX_CORE
    description: "Transação PIX (E2E/TXID/CHAVE)."
    regexes:
      - regex: "\bPIX\b"              # marca simples
        captures: []
      - regex: "\bE2E\s*ID[:\s-]*([A-Z0-9-]{20,36})\b"
        captures: [pix_e2e]
      - regex: "\bTXID[:\s-]*([A-Z0-9-]{4,35})\b"
        captures: [pix_txid]
      - regex: "\bCHAVE\s*PIX[:\s-]*([A-Z0-9@._-]{6,})\b"
        captures: [pix_key]
  - id: TED_DOC
    description: "Transferência bancária: TED/DOC/TEV + possível protocolo."
    regex: "\b(?:TED|DOC|TEV|TRANSFER[ÊE]NCIA)\b(?:.*?\b(?:ID|PROTOC(?:O|Ó)LO)[:\s-]*([A-Z0-9-]{6,}))?"
    captures: [bank_ref]
  - id: CARTAO_ADQ
    description: "Captura de adquirentes (CIELO/REDE/GETNET/STONE/...). Extrai NSU/Aut."
    regex: "\b(?:CIELO|REDE|GETNET|STONE|PAGSEGURO|SAFRA\s*PAY|BIN|ELAVON)\b.*?\b(?:NSU|NRO\s*AUT|AUT(?:ORIZACAO)?)[:\s-]*([0-9A-Z]{6,12})"
    captures: [nsu]
  - id: BOLETO_LINHA
    description: "Boleto (linha digitável)."
    regex: "\b(?:BOLETO|LINHA\s*DIGITAVEL)[:\s-]*([0-9.\s]{30,60})"
    captures: [linha]
    post:
      linha_digits: "digits(linha)"
  - id: NFSE_RPS
    description: "NFS-e/RPS com número e série."
    regex: "\b(?:NFS?-?E|RPS)\s*(\d{1,12})(?:[\/\-](\d{1,3}))?\b"
    captures: [doc_num, doc_serie]
    post:
      doc_num_norm: "digits(doc_num)"
      doc_serie_norm: "lstrip_zeros(doc_serie)"
  - id: CHAVE_NFE_44
    description: "Chave de acesso NFe (44 dígitos)."
    regex: "\b(?:CHAVE(?:\s+DE\s+ACESSO)?|CHAVE\s*NFE)[:\s-]*([0-9\s.]{30,60})"
    captures: [chave_raw]
    post:
      chave_44: "digits(chave_raw, expect_len=44)"

compositions:
  # Como decidir doc_num_norm a partir de múltiplos indícios
  - id: DOC_BEST_GUESS
    prefer_order: [NFE_NUM_SERIE, DCTO_NUM, FATURA_NUM, DUPLICATA_NUM, NFSE_RPS]
    derive:
      doc_num_norm: "first_available(doc_num_norm)"
      doc_serie_norm: "first_available(doc_serie_norm)"
  # Estratégia de agrupamento bancário (para N:1 em pagamentos)
  - id: BANK_MERGE_DAY_TOKEN
    applies_to: [PIX_CORE, TED_DOC, CARTAO_ADQ]
    group_by:
      - "date_floor(DAY)"
      - "participante_cod_or_name"
      - "coalesce(pix_e2e, pix_txid, pix_key, bank_ref, nsu)"
    sum_tolerance_ref: "tolerancias.FONTE|CONTA|GLOBAL"
    notes: "Usado para casar liquidações parciais/múltiplas a uma fatura única."

score_boosts:
  NFE_NUM_SERIE: 12
  DCTO_NUM: 10
  FATURA_NUM: 8
  DUPLICATA_NUM: 6
  NFSE_RPS: 10
  CHAVE_NFE_44: 5        # útil como indício adicional
  PIX_CORE: 8
  TED_DOC: 6
  CARTAO_ADQ: 10
  BOLETO_LINHA: 4

tests:
  - input: "PAGTO NFE 14959/002 DCTO14959 PIX CHAVE PIX: odival@exemplo.com"
    expect_tokens:
      NFE_NUM_SERIE: {doc_num_norm: "14959", doc_serie_norm: "2"}
      DCTO_NUM: {doc_num_norm: "14959"}
      PIX_CORE: {pix_key: "ODIVAL@EXEMPLO.COM"}
  - input: "CIELO VDA CREDITO NSU 123456 VALOR 1.234,56"
    expect_tokens:
      CARTAO_ADQ: {nsu: "123456"}
  - input: "BOLETO LINHA DIGITAVEL 23793.38127 60000.000136 61009.510903 6 74120000012345"
    expect_tokens:
      BOLETO_LINHA: {linha_digits: "2379338127600000013661009510903674120000012345"}
  - input: "NFS-e 9876-1 PRESTADOR: SERVICOS ALFA LTDA"
    expect_tokens:
      NFSE_RPS: {doc_num_norm: "9876", doc_serie_norm: "1"}

