# Tolerâncias e janelas de conferência
# Contextos aceitos: GLOBAL, CONTA, CFOP, FONTE, PARTICIPANTE
# Notação:
#   tol_abs  -> tolerância absoluta (moeda)
#   tol_pct  -> tolerância percentual (fração, ex.: 0.002 = 0,2%)
#   janela_dias -> janela de datas (|data_sucessor - data_fonte| <= N dias)
#   arredondamento -> casas decimais ao comparar (2..4)
#   parcelas:
#       habilitado: true/false  (permitir N:1 por documento)
#       tol_sum_abs/tol_sum_pct (tolerância para soma de parcelas vs valor do doc)
#       max_parcelas: inteiro (0 = sem limite explícito)
#   observacoes -> livre (texto)

GLOBAL: &GLOBAL
  moeda: "BRL"
  tol_abs: 0.01
  tol_pct: 0.002         # 0,2%
  janela_dias: 3
  arredondamento: 2
  parcelas:
    habilitado: true
    tol_sum_abs: 0.05
    tol_sum_pct: 0.003  # 0,3%
    max_parcelas: 24
  observacoes: "Padrão do projeto; ajusta centavos residuais e deslocamentos de D+/-3"

# Por CONTA (código do plano, alias opcional). Prioridade > GLOBAL
CONTA:
  # Contas com taxas/juros têm margem um pouco maior
  - chave: "1.1.1.01.0001"         # Caixa
    <<: *GLOBAL
    tol_abs: 0.02
  - chave: "1.1.1.02.0001"         # Bancos movimento
    <<: *GLOBAL
    tol_abs: 0.05
    tol_pct: 0.004                 # 0,4%
  - chave: "3.1.1.01.0001"         # Receita cartão
    <<: *GLOBAL
    tol_abs: 0.10
    tol_pct: 0.006                 # 0,6% para variações de taxas
    observacoes: "Liquidações de cartão (CIELO/NSU) sofrem variação por tarifa"

# Por CFOP. Prioridade > CONTA > GLOBAL
CFOP:
  - chave: "1102"   # Compra para revenda
    <<: *GLOBAL
    tol_abs: 0.02
  - chave: "1556"   # Ativo imobilizado
    <<: *GLOBAL
    janela_dias: 7  # compras grandes tendem a ter compensações em datas diferentes
  - chave: "5102"   # Venda de mercadoria
    <<: *GLOBAL
    tol_abs: 0.02
    tol_pct: 0.003

# Por FONTE (planilhas específicas). Prioridade > CFOP > CONTA > GLOBAL
# Valores típicos de fontes: ENTRADA, SAIDA, SERVICO
FONTE:
  - chave: "ENTRADA"
    <<: *GLOBAL
    janela_dias: 4
  - chave: "SAIDA"
    <<: *GLOBAL
    janela_dias: 3
  - chave: "SERVICO"
    <<: *GLOBAL
    janela_dias: 5
    tol_abs: 0.02

# Por PARTICIPANTE (código ou CNPJ). Prioridade > FONTE > CFOP > CONTA > GLOBAL
PARTICIPANTE:
  - chave: "04502123000189"   # CNPJ Oxigênio Modelo (exemplo)
    <<: *GLOBAL
    janela_dias: 5
    observacoes: "Fornecedor com atrasos sistêmicos de baixas; janela maior"

# Estratégias específicas (ajustes finos para S1..S5) — opcional
# Se omitido, herda as tolerâncias acima.
estrategias:
  S1:
    <<: *GLOBAL
  S2:
    <<: *GLOBAL
    janela_dias: 3
  S3:
    <<: *GLOBAL
    janela_dias: 3
  S4:
    <<: *GLOBAL
    janela_dias: 2
  S5:
    <<: *GLOBAL
    tol_abs: 0.02

# Perfil por cliente/período (sobrepõe tudo acima quando ativo)
# Ativar passando 'perfil_ativo' na configuração do projeto.
perfis:
  ms_oxigenio_2025_09:
    GLOBAL:
      <<: *GLOBAL
      janela_dias: 4
    CONTA:
      - chave: "3.1.1.01.0001"
        <<: *GLOBAL
        tol_pct: 0.007
        tol_abs: 0.15
        observacoes: "Liquidações cartão c/ taxa variável — setembro/2025"
    CFOP:
      - chave: "1102"
        <<: *GLOBAL
        tol_abs: 0.03
    FONTE:
      - chave: "ENTRADA"
        <<: *GLOBAL
        janela_dias: 5
    PARTICIPANTE:
      - chave: "04502123000189"
        <<: *GLOBAL
        janela_dias: 6

